### ISSUE TITLE
Support ESP microcontroller or Pi Pico W

### ISSUE THREAD

**Issue by Dozentz** [kimmobrunfeldt/eink-weather-display#6]
I liked the design of the weather display. Tell me how you can do it on a more budget ESP microcontroller or support Raspberry Pi Pico, as well as reduce the screen with support for 7.5 inch displays. And also enable support for Open Weather Map. It would be nice to add a BME280 temperature sensor to display the temperature and humidity in the room

**Comment by kimmobrunfeldt** [comment]
Thanks! I chose to use a Raspberry PI Zero because it can run full Python etc. It makes many things easier. I don't have experience with microcontrollers so can't help with that. At least Waveshare displays have C drivers for each size, you can check their site and wiki. Also https://inkplate.io/ looked like an interesting project. It could suit your purposes.

Open Weather Map support is not required for my use case, but feel free to integrate to their API. The code already integrates to [Open Meteo](https://github.com/open-meteo/open-meteo) API which is also open source.

I'm not sure how long the battery would last using a microcontroller, but definitely longer than with Raspberry Pi Zero. It could be feasible to display sensor data updated e.g. every 10 minutes. Or then connect the device to external power.

Hopefully this project inspires you to make a microcontroller version! This repository is just intended for our use case and I have no plans to expand this repo to support anything we don't use at our home. For that purpose, this repo can be forked.
